# Usamos Tomcat como servidor web
FROM tomcat:10-jdk17-openjdk-slim

# Borramos la web que trae Tomcat por defecto
RUN rm -rf /usr/local/tomcat/webapps/ROOT

# Copiamos tu archivo .war a la carpeta de despliegue de Tomcat
# Asegúrate de que el nombre coincida con el que tienes en /target
COPY target/*.war /usr/local/tomcat/webapps/ROOT.war

# Exponemos el puerto 8082
EXPOSE 8082